about/urls.py
from django.urls import path
from .views import about

urlpatterns = [
    path('about/', about, name="about"),
]

certifications/urls.py
from django.urls import path
from .views import certifications

urlpatterns = [
    path('certifications/', certifications, name="certifications"),
]

homepage/urls.py
from django.urls import path
from .views import homepage

urlpatterns = [
    path('', homepage, name="homepage")
]

main/urls.py
from django.urls import path
from . import views

app_name = "main"

urlpatterns = [
    path("", views.homepage, name="homepage"),
    path("contact", views.contact, name="contact"),

]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('homepage.urls')),
    path('about/', include('about.urls')),
    path('certifications/', include('certifications.urls')),
    path('contact/', include('main.urls')),
    path('skills/', include('skills.urls')),

]

skills/urls.py
from django.urls import path
from .views import skills

urlpatterns = [
    path('skills/', skills, name="skills"),
]

about/models.py
from django.db import models

# Create your models here.

certifications/models.py
from django.db import models

# Create your models here.

homepage/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models

# Create your models here.

skills/models.py
from django.db import models

# Create your models here.

main/forms.py
from django import forms

# Create your forms here.

class ContactForm(forms.Form):
	first_name = forms.CharField(max_length = 50)
	last_name = forms.CharField(max_length = 50)
	email_address = forms.EmailField(max_length = 150)
	message = forms.CharField(widget = forms.Textarea, max_length = 2000)

about/views.py
from django.shortcuts import render


def about(request):
    return render(request, 'about.html')

certifications/views.py
from django.shortcuts import render


def certifications(request):
    return render(request, 'certifications.html')

homepage/views.py
from django.shortcuts import render


def homepage(request):
    return render(request, 'homepage.html')

main/views.py
from django.shortcuts import render, redirect
from .forms import ContactForm
from django.core.mail import send_mail, BadHeaderError
from django.http import HttpResponse


# Create your views here.
def homepage(request):
    return render(request, "homepage.html")


def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            subject = "Website Inquiry"
            body = {
                'first_name': form.cleaned_data['first_name'],
                'last_name': form.cleaned_data['last_name'],
                'email': form.cleaned_data['email_address'],
                'message': form.cleaned_data['message'],
            }
            message = "\n".join(body.values())

            try:
                send_mail(subject, message, 'admin@example.com', ['admin@example.com'])
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
            return redirect("main:homepage")

    form = ContactForm()
    return render(request, "contact.html", {'form': form})

skills/views.py
from django.shortcuts import render

def skills(request):
    return render(request, 'skills.html')

templates/about.html
{% extends 'base.html' %}
{% block page_about %}
    {% load static %}

<main>

<div>
    <div class="about-me">
      <div class="about-me-text">
        <h2>About Me</h2>
        <p>I’m a computer programmer who is passionate about writing code, solving problems, automating and building software.</p>
      </div>

      <img src="/static/images/me.jpg" alt="me">
    </div>

</main>

 {% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<!-- Starts Head Section -->

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">

  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>www.niki9011.bg</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link rel="stylesheet" href="/static/css/homepage.css">

</head>
<!-- End Head Section -->

<!-- Starts Navbar Section -->
<body>
  <header class="header">
{#    <img src="/static/images/o.png">#}
      <a href="{% url 'homepage' %}" class="logo" >Python Developer</a>
    <nav class="nav-items">
      <a href="{% url 'homepage' %}">Home</a>
      <a href="{% url 'about' %}">About</a>
      <a href="{% url 'certifications' %}">Certificates</a>
      <a href="{% url 'main:contact' %}">Contact</a>
    </nav>

  </header>
  <!-- End Navbar Section -->

<!-- Starts Main Section -->
<main>
    {% block page_content %}
    {% endblock %}
{##}
{% block page_contact %}
    {% endblock %}

{% block page_about %}
    {% endblock %}

{% block page_certifications %}
    {% endblock %}

{% block page_skills %}
    {% endblock %}
</main>
<!-- End Main Section -->

  <!-- Starts Footer Section -->
<footer class="footer">
    <div class="copy">&copy; 2023 Nikolay Videnov</div>
        <a href="https://github.com/niki9011"><i class="fab fa-github fa-2x" style="color:white" ></i></a>
        <a href="https://www.linkedin.com/in/nikolay-videnov-968648239/"><i class="fab fa-linkedin fa-2x" style="color:white"></i></a>
        <a href="https://www.facebook.com/nikolai.videnov/"><i class="fab fa-facebook fa-2x" style="color:white"></i></a>
    </div>
  </footer>
<!-- End Footer Section -->

</body>

</html>

templates/certifications.html
{% extends 'base.html' %}
{% block page_certifications %}
{% load static %}

<main>
{#<link rel="stylesheet" href="/static/css/certifications.css">#}

{#    <img src="/static/images/certif-logo.jpg">#}

{#<img src="/static/images/certif-logo.jpg">#}
<meta name="viewport" content="width=device-width, initial-scale=1">

    <body>
<div class="slideshow-container">

<div class="mySlides fade">
 <center><img src="/static/images/basics.jpg" alt="centered image" height="750" width="500"> </center>
 <center> <div class="numbertext">1 / 4</div></center>
{#  <img src="/static/images/basics.jpg" style="width: 500px; height: 750px">#}

</div>

<div class="mySlides fade">
  <center><img src="/static/images/fundamentals.jpg" alt="centered image" height="750" width="500"> </center>
  <center><div class="numbertext">2 / 4</div></center>

{#  <img src="/static/images/fundamentals.jpg" style="width: 500px; height: 750px">#}

</div>

<div class="mySlides fade">
 <center><img src="/static/images/advanced.jpg" alt="centered image" height="750" width="500"> </center>
 <center> <div class="numbertext">3 / 4</div></center>

{#  <img src="/static/images/advanced.jpg" style="width: 500px; height: 750px" >#}

</div>
    <div class="mySlides fade">
  <center><img src="/static/images/oop.jpeg" alt="centered image" height="750" width="500"> </center>
  <center></center><div class="numbertext">4 / 4</div> </center>

{#  <img src="/static/images/oop.jpeg" style="width: 500px; height: 750px">#}

</div>

</div>
<br>

    <script>
var myIndex = 0;
carousel();

function carousel() {
  var i;
  var x = document.getElementsByClassName("mySlides");
  let dots = document.getElementsByClassName("dot");
  for (i = 0; i < x.length; i++) {
    x[i].style.display = "none";

  }
  myIndex++;
  if (myIndex > x.length) {myIndex = 1}
  x[myIndex-1].style.display = "block";
  setTimeout(carousel, 2000); // Change image every 2 seconds
}
</script>

</body>
</main>

 {% endblock %}

templates/contact.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% block page_contact %}
{% load static %}

<main>

<style>

* {box-sizing: border-box;}
body {font-family: Arial, Helvetica, sans-serif;
         background-color: rgb(255, 255, 255);
    box-sizing: border-box;
      }
</style>


<meta name="viewport" content="width=device-width, initial-scale=1">
{#    <link rel="stylesheet" href="/static/css/contact.css">#}

<!--Contact form-->

{#	<div style="margin:0">#}
<table>

</div>


    <center><img src="/static/images/contact.png" style="width:550px"></center>
{#		<h1>Contact</h1>#}
<center>
		<form method="post">
        {% csrf_token %}
            {{form.as_p}}
            <button type="submit">Submit</button>
        </form>

    <div class="bottom-links">
    <div class="bottom-links">
    <div class="bottom-links">
{#      <div class="links">#}
{#        <span>Social Links</span>#}
{#          <img src="/static/images/main.png" style="width:100%">#}
{#        <a href="https://github.com/niki9011"><i class="fab fa-github fa-1.5x" style="color:black" ></i></a>#}
{#        <a href="https://www.linkedin.com/in/nikolay-videnov-968648239/"><i class="fab fa-linkedin fa-1.5x" style="color:#0077b5"></i></a>#}
{#        <a href="https://www.facebook.com/nikolai.videnov/"><i class="fab fa-facebook fa-1.5x" style="color:#3F51B5"></i></a>#}
      </div>
        <center>
</table>

</main>

 {% endblock %}

templates/homepage.html
{% extends 'base.html' %}
{% block page_content %}
    {% load static %}
{##}
{#<main>#}
{#    <div class="intro">#}
{##}
{#<marquee><h1>HI, I AM NIKOLAY.</h1></marquee>#}
{#        <marquee#}
{#  direction="down"#}
{#  width="350"#}
{#  height="200"#}
{#  behavior="alternate"#}
{#  style="border:moccasin">#}
{#  <marquee behavior="alternate"> <p>Welcome to my portfolio.</p></marquee>#}
{#</marquee>#}

{##}
{#    </div>#}
{##}
{##}
{#    <div class="achievements">#}
{#      <div class="work">#}
{#          <a class="btn btn-large btn-primary logout" href="https://softuni.bg/blog/success-story-2023-un-project?fbclid=IwAR1Rs-pR9PkD2jYXF-oByjj8nYHNpkw4fIPYyRQqMBdeSrIle7DepSL12nw#">#}
{#            <i class="fas fa-atom" aria-hidden="true"></i>#}
{#            <p class="work-heading">Projects</p>#}
{#      </div>#}
{##}
{##}
{##}
{#      <div class="work">#}
{#          <a class="btn btn-large btn-primary logout" href="{% url 'skills' %}">#}
{#            <i class="fas fa-skiing"></i>#}
{#            <p class="work-heading">Skills</p>#}
{#               <div class="work">#}
{##}
{#      </div>#}
{#</a>#}
{##}
{#              <div class="about-me">#}
{#      <div class="about-me-text">#}
{#        <h2>About Me</h2>#}
{#        <p>I’m a computer programmer who is passionate about writing code, solving problems, automating and building software.</p>#}
{#      </div>#}
{##}
{#      <img src="/static/images/me.jpg" alt="me">#}
{#    </div>#}
{##}
{#</a>#}

{#    <div class="about-me">#}
{#      <div class="about-me-text">#}
{#        <h2>About Me</h2>#}
{#        <p>I’m a computer programmer who is passionate about writing code, solving problems, automating and building software.</p>#}
{#      </div>#}
{##}
{#      <img src="/static/images/me.jpg" alt="me">#}
{#    </div>#}

{#          <div class="about-me">#}
{#      <div class="about-me-text">#}
{#           <img src="/static/images/me.jpg" alt="me">#}
{#        <h2>About Me</h2>#}
{#        <p>I am a web developer and I love to create websites. I am a very good developer and I am always looking for new projects. I am a very good developer and I am always looking for new projects.</p>#}
{#      </div>#}
{#      <img src="/static/images/me.jpg" alt="me">#}
{#    </div>#}


{#    </div>#}
{#    <div class="about-me">#}
{#      <div class="about-me-text">#}
{#        <h2>About Me</h2>#}
{#        <p>I’m a computer programmer who is passionate about writing code, solving problems, automating and building software.</p>#}
{#      </div>#}
{#      <img src="/static/images/me.jpg" alt="me">#}
{#    </div>#}


{#    <div class="achievements">#}
{#      <div class="work">#}
{#        <i class="fas fa-atom"></i>#}
{#        <p class="work-heading">Projects</p>#}
{#        <p class="work-text">I have worked on many projects and I am very proud of them. I am a very good developer and I am always looking for new projects.</p>#}
{#      </div>#}
{#      <div class="work">#}
{#        <i class="fas fa-skiing"></i>#}
{#        <p class="work-heading">Skills</p>#}
{#        <p class="work-text">I have a lot of skills and I am very good at them. I am very good at programming and I am always looking for new skills.</p>#}
{#      </div>#}
{#      <div class="work">#}
{#        <i class="fas fa-ethernet"></i>#}
{#        <p class="work-heading">Network</p>#}
{#        <p class="work-text">I have a lot of network skills and I am very good at them. I am very good at networking and I am always looking for new network skills.</p>#}
{#      </div>#}
{#    </div>#}
{#    <div class="about-me">#}
{#      <div class="about-me-text">#}
{#        <h2>About Me</h2>#}
{#        <p>I am a web developer and I love to create websites. I am a very good developer and I am always looking for new projects. I am a very good developer and I am always looking for new projects.</p>#}
{#      </div>#}
{#      <img src="/static/images/me.jpg" alt="me">#}
{#    </div>#}
{#  </main>#}
    <main>

    <div class="intro">
{#         <img src="/static/images/az.jpg">#}

<marquee><h1>HI, I AM NIKOLAY.</h1></marquee>
        <marquee

  direction="down"
  width="350"
  height="200"
  behavior="alternate"
  style="border:moccasin">
  <marquee behavior="alternate"> <p>Welcome to my portfolio.</p></marquee>
</marquee>

    </div>

    <div class="achievements">
      <div class="work">
{#          <a class="" href="{% url 'skills' %}">#}
          <button onclick="window.location.href='https://sdsn.bg/bg/';"><i class="fas fa-atom" ></i></button>

{#        <i class="fas fa-atom"></i>#}
        <h2 class="work-heading">Project</h2>
        <p class="work-text">I have worked on many projects and I am very proud of them. I am a very good developer and I am always looking for new projects.</p>
      </div>
      <div class="work">
          <button onclick="window.location.href='{% url 'skills' %}';"><i class="fa fa-skiing" ></i></button>
        <h2 class="work-heading" >Skills</h2>
        <p class="work-text">I have a lot of skills and I am very good at them. I am very good at programming and I am always looking for new skills.</p>
      </div>
      <div class="work">
          <button onclick="window.location.href='https://softuni.bg/blog/success-story-2023-un-project?utm_source=linkedin&utm_medium=organic&utm_campaign=success-stories&utm_term=blog&utm_content=%D0%BE%D0%BE%D0%BD#';"><i class="fa fa-newspaper" ></i></button>
        <h2 class="work-heading">Interview</h2>
        <p class="work-text">SoftUni students realized a project for the United Nations.</p>
      </div>
    </div>
    <div class="about-me">
      <div class="about-me-text">
          <img src="/static/images/aboutme.jpg" alt="me">
{#        <h2>About Me</h2>#}
        <p>I am a web developer and I love to create websites. I am a very good developer and I am always looking for new projects. I am a very good developer and I am always looking for new projects.</p>
      </div>
      <img src="/static/images/me.jpg" alt="me">
    </div>
  </main>

 {% endblock %}

templates/skills.html
{% extends 'base.html' %}
{% block page_skills %}


    <main>

<div>
    <style>
h2 {text-align: center;}
</style>

<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
{#    <div class="about-me">#}
      <div class="about-me-text">
          <p style="text-align:center;"><img src="/static/images/skills2.jpg" alt="me" style="width:950px">
{#        <h2></h2>#}
        <h2>&#8226; HTML</h2>
        <h2>&#8226; CSS</h2>
        <h2>&#8226; WordPress</h2>
        <h2>&#8226; Django</h2>
        <h2>&#8226; PostgresSQL</h2>
        <h2>&#8226; Docker</h2>
        <h2>&#8226; Linux</h2>
        <h2>&#8226; Git</h2>
        <h2>&#8226; XAMPP</h2>
        <h2>&#8226; Windows</h2>

      </div>

    </div>

</main>

 {% endblock %}